### PR TITLE
fix endless skin loading on error

### PR DESCRIPTION
**Pull request by SiverDX**
fixes the endless loading for #384 (but the skins themselves are probably still missing)

### CODE REVIEW

**Comment by BlackAures1** [comment]
srinater's doing it now
 
 
image

**Comment by SiverDX** [comment]
this change should be merged regardless

**Comment by FirDragon** [comment]
When testing, be sure to confirm loading from gitcode. My code logic is that when gitcode cannot be loaded, it will be accessed through github, so loading outside China will succeed no matter what.

**Comment by FirDragon** [comment]
You need to comment out the code loaded from github and retest

**Comment by FirDragon** [comment]
At the same time, you must ensure that you can access the gitcode websit

**Comment by FirDragon** [comment]
The result of my test here is that the API interface of gitcode has changed.
image

**Comment by FirDragon** [comment]
gitcode migrated the mirrors project to another API

**Comment by FirDragon** [comment]
I'm in China, leave this job to me

**Comment by FirDragon** [comment]
At the same time, I discovered a new problem: the maximum limit of GitHub's enumerated file API is 1,000, but our skin volume has far exceeded 1,000. This resulted in more than half of the skins not being listed through the api at api.github.com

**Comment by FirDragon** [comment]
Should be updated to https://api.github.com/repos/:OWNER/:REPO/git/trees/:tree_sha

**Comment by BlackAures1** [comment]
> At the same time, I discovered a new problem: the maximum limit of GitHub's enumerated file API is 1,000, but our skin volume has far exceeded 1,000. This resulted in more than half of the skins not being listed through the api at api.github.com

Hmm, I haven't gotten any reports of someone's skins not showing up yet. Considering there are over 2100 skin files already, someone would have reported the problem

**Comment by SiverDX** [comment]
if i understand it correctly it only affects the SKIN_USERS variable which is used for gitcode and the randomizer (showing skins from random players)

**Comment by BlackAures1** [comment]
That not all skins are specified in randomization is true, but this was also the case before the 1000 texture mark. Many specific nicknames do not appear

**Comment by FirDragon** [comment]
ok they are all fixed

**Comment by BlackAures1** [comment]
Currently causes a crash when clicking on random (sometimes, not all the time)
[crash-2023-11-24_16.28.20-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13460534/crash-2023-11-24_16.28.20-client.txt)
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/13460535/latest.log)

**Comment by SiverDX** [comment]
seems to hit the api rate limit

`querySkinImage` shouldn't catch the `IOException`
Prevents `fetchSkinFile` from handling null streams and runs its error handling

**Comment by SiverDX** [comment]
generally i would recommend to recheck https://github.com/DragonSurvivalTeam/DragonSurvival/pull/386 since that introduced this issue and i also saw some issues with glow layers for non-custom skins

**Pull request merged**
