### PR TITLE
Various things

### PR DESCRIPTION
**Pull request by SiverDX**
Fire breath
- Now calls `onCaughtFire` for the affected blocks
  - meaning it can ignite tnt
  - Only happens when mob griefing is enabled

Forest breath
- Config (true by default) to allow dirt transformation (blocks to transform to can be configured)
- Grass is no longer exempt from the bonemeal logic
  - (Since modded grass is not exempted either)

When using the dragon editor as a player the initial size will be `Newborn`
- Initially I thought there was a desync between editing skins as player and dragon but it's just that the player starts as `Young` since the player size is usually at least 20
  - Setting the default size to `Newborn` seems to make more sense since that is what you're going to start as
  - Also refactored that part a bit
- Made the `DragonStateHandler` static to prevent it from creating new ones everytime the GUI gets opened (and they're being kept around)

Setting the harvest speed bonus no longer discards changes made to the block break speed by other mods
- Affects things like enchantments, attributes and other things mods can do

Made the mixin responsible for turning cave dragon block drops fire immune more compatible
- Previously this logic skipped the teleport handling for the Apotheosis Telepathic effect among other things

Added a config for food which should keep their effects (and are exempt from the hunger effect config)
- Their (negative) nutrition / saturation remains unchanged
- Useful for items like the wine from Vinery or items which use their effects to trigger something mod related

Fixed an instance where the dimension (size) could desync between server and client (could be triggered by using a command to turn yourself into a dragon and then logging out and back in)
- The issue would cause you to be unable to get close to blocks among other things

Added some explicit calls to rebuild certain configs to make sure changes to the config get immediately applied

Fixed an issue where broken tools were not properly removed form the claw inventory

### CODE REVIEW

**Comment by BlackAures1** [comment]
> Grass is no longer exempt from the bonemeal logic
What was the reasoning behind this decision? Disabling grass growth for the forest was done to make combat easier, as grass growth during combat was very annoying.

**Comment by SiverDX** [comment]
added them to the config meaning they're at least no longer hardcoded

**Comment by BlackAures1** [comment]
Question, can I merge this with the main branch or are you planning on fixing something?

**Comment by SiverDX** [comment]
don't have anything planned and didn't encounter any further problems so far

**Pull request merged**
