### PR TITLE
Stop trying to sync player data on login/respawn/dimension change. Only allow reading data from the server in those situations.

### LINKED ISSUE #468: [1.19.2 Bug]: Getting turned to human from dragon when reconnecting to a server, teleporting, or dying.
### ■ Your Discord ID or other contacts

lyrth

### ■ Dragon Survival version

DragonSurvival-1.19.2-02.03.2024_stable

### ■ Single game or server?

Host site

### ■ Describe the bug

Getting turned to human from dragon when reconnecting to a server, teleporting (across dimensions - using Waystones mod objects), or dying (and respawning).

Most of the time, I am shown the "Choose a Dragon Species" menu after turning into a human when doing any of the above. 

***Exiting*** the species select menu will make the player human. Either of the two happens:
- Disconnecting from the server quick enough and rejoining will ***restore*** dragon form and progress. Used to happen before, but does not anymore. ***Dev note:*** in this state, the dragon stats in the player NBT data (type/age/skills/presets/etc under `ForgeCaps/dragonsurvival:playerstatehandler`) are KEPT intact.
- Player will retain human form, and still will even with reconnect/death/teleport. ***Dev note:*** in this state, dragon stats in player NBT data are CLEARED (type: none, cave/forest/seaSize are 0, skinPreset also reset to all None).

***Selecting*** a species and saving (cave dragon in my case) will OVERWRITE my dragon age/skills/etc. with a newborn's. Not good either.

A player data backup was made back when I have the proper dragon form, age, and progress. Player data NBT looks correct and fine too. That same backup is then used to replace my player data on the server, BUT when I join the server, it often makes me join as a human player. **On the other hand,** another player using my same exact player data (from the backup) on their character works fine for them even after multiple reconnects.

I have tried using a different launcher (curseforge, multimc), different and fresh install location too. Problem persists.

### ■ Crash Report File and Logs

Being turned human happened as soon as the chat entry `NO AM HUMAN AGAIN` appears in the log, both client and server. No crash.

[Client log](https://gist.githubusercontent.com/Lyrth/8d0ff4d7a7e549b7d188ae97818cda26/raw/3865f8e69540e6988f8452129e51c1282f0b5707/client_nochat.log)

[Server log](https://gist.githubusercontent.com/Lyrth/8d0ff4d7a7e549b7d188ae97818cda26/raw/3865f8e69540e6988f8452129e51c1282f0b5707/server_nochat.log)

### PR DESCRIPTION
**Pull request by seelderr**
There is an underlying problem here where it is possible for the client to write data to the server before it has read data from the server. This should fix this situation in 99% of cases. However, it is still possible for the client to do an action that requires a sync after logging in but before receiving dragon data from the server, in which case their data will still get lost.

Would be a good idea to extend this fix in the future by explicitly checking if the player has read from the server (or is creating their dragon for the first time) before allowing any writes of dragon data to the server.

fixes #468

### CODE REVIEW

**Comment by Zhusiyuan354** [comment]
It seems doesn't work well in future version.Sometimes it would still lose players' data.

**Comment by seelderr** [comment]
This was already reverted a bit later, didn't get mentioned

**Comment by seelderr** [comment]
See https://github.com/DragonSurvivalTeam/DragonSurvival/blob/1.20.1/src/main/java/by/dragonsurvivalteam/dragonsurvival/common/capability/Capabilities.java

**Comment by AtlasSniper121** [comment]
> There is an underlying problem here where it is possible for the client to write data to the server before it has read data from the server. This should fix this situation in 99% of cases. However, it is still possible for the client to do an action that requires a sync after logging in but before receiving dragon data from the server, in which case their data will still get lost.
> 
> Would be a good idea to extend this fix in the future by explicitly checking if the player has read from the server (or is creating their dragon for the first time) before allowing any writes of dragon data to the server.
> 
> fixes #468

how do i apply this fix? i see that theres some lines to copy, but where do i paste those?

**Pull request merged**
