### PR TITLE
Fixes and other things

### PR DESCRIPTION
**Pull request by SiverDX**
### BetterCombat related
* Only re-enable Sweep if the weapon can perform Sweep
* Don't hide dragon model if any sort of screen is open

### Fixed some issues regarding abilities (GUI)
* Tooltip coloring for increasing levels
* Experience gained from decreasing was 1 level lower than intended
* There were 2 additional SkillProgressButtons being rendered (but overlayed by other buttons)
* Right side of the experience cost for abilities had the wrong start location
* When increasing or decreasing ability levels all were shown as obtainable (until screen was re-opened)

### Other
* Removed bad omen application when you kill a knight (only occurred as a non-dragon)
* Fixed some issue with water cauldron block (sea dragon gained no good mana condition from it)

### Fixed a bug with the `Claws and Teeth` description
* The harvest level text was not accurate (starting from gold? it was 1 level too high)

### Fixed issues with harvesting
* Modded ore support for drops when only using paws
* Config for `bonusUnlockedAt` is now respected
* ServerConfig.baseHarvestLevel is now actually used

### Mod support
* Harvest information support for Jade and WHIT Harvestability

---

Seemed fine on client and server
Should still make sure to test this

### CODE REVIEW

**Comment by BlackAures1** [comment]
> // FIXME :: Why is the sword ignored? It can harvest cobwebs (and due to other mods maybe other things as well)

The fact that sword mining is ignored is a bug

> (BlockTags.NEEDS_DIAMOND_TOOL)
Why is diamond tools mentioned here? Dragons are available at most stone

I'll check the rest a bit more later. 
Question, 
1. have you checked how the `alternateHeldItem` configuration works with Better Combat?
2. `renderFirstPerson` config not copy of `hideDragonModel`?

**Comment by SiverDX** [comment]
`int harvestLevel = blockState.is(BlockTags.NEEDS_DIAMOND_TOOL) ? 3 : blockState.is(BlockTags.NEEDS_IRON_TOOL) ? 2 : blockState.is(BlockTags.NEEDS_STONE_TOOL) ? 1 : 0;`

This line determines the required harvest level of the block based on the tag it's part of
I did not change this, though I could imagine it not being wholly accurate since it requires for mods to actaully set that tag (MCreator lol)

---

`hideDragonModel` from an idea point is a duplicate but I added it because `renderFirstPerson` does things too late / in a different way

the new option just skips the rendering

**Comment by SiverDX** [comment]
Funnily enough in

https://github.com/SiverDX/DragonSurvival/blob/89e4778260c8a4f43321990c1f88512c748f0ca0/src/main/java/by/dragonsurvivalteam/dragonsurvival/client/render/ClientDragonRender.java#L151

if you don't cancel the event and set `renderPlayerEvent.getRenderer().getModel().setAllVisible(false);` the Better Combat weapon / attack animation will be visible

Though it will be a bit too high for smaller dragons and too low for bigger dragons
And the weapon gets rendered twice (once in the dragon survival way and once in the original or better combat way? not sure)

**Comment by SiverDX** [comment]
Regarding https://github.com/DragonSurvivalTeam/DragonSurvival/pull/336/commits/651c649331a2bd491e7fa44429026fae81d22c56

Is `ServerConfig.bonusUnlockedAt` supposed to ignore the effectivness of the dragon type for the specific block when it comes to break speed?

Meaning is a forest dragon supposed to be able to mine Stone etc. faster?
For the harvest level this is not the case but for break speed it did have an effect

For adult dragons the check was used to give them a 4x multiplier for their specific block type instead of a 2x multiplier (which applied to all blocks)

**Comment by BlackAures1** [comment]
I can't exactly answer your question, but I can describe the prey to you fully as it was conceived. The rest is up to you. Make sure that the configs associated with it all have not been broken due to changes and players can change it if they wish in the settings.

The most important thought and concept is that dragons have teeth and claws that humans don't have. For this reason, dragons are better at mining blocks and more painful to bite by default.

1. Innate harvest bonus for dragons. This applies when the dragon has nothing in the claw slot. 

2. Claw slots - these override dragon innate bonuses. Does not stack with Innate bonus.

3 Both work even with blocks and items in the hotbar. Not necessarily just with a bare paw. When selecting a tool/weapon in the hotbar, innate bonus and claw bonus do not add up and have no effect on characteristics.

Examples:
- Adult cave dragon digs with block/item in hotbar (claws empty) - damage: 3, stone pickaxe, wooden shovel, wooden axe
- Young cave dragon dig with empty hotbar (claws empty) - damage: 2, stone pickaxe, wooden shovel, wooden axe
- Newborn sea dragon (diamond pickaxe in claw slot) - Damage: 1, diamond pickaxe, wooden shovel, wooden axe
- Adult sea dragon (selected wooden shovel in hotbar, diamond shovel in claw slot) - damage: 2.5, wooden pickaxe, wooden shovel, wooden axe
- Young forest dragon (selected diamond shovel in hotbar, diamond axe in claw slot) - damage: 5.5, wooden pickaxe, diamond shovel, diamond axe

**Comment by SiverDX** [comment]
### Harvest Speed modification
The way it works right now is that if you have a tool in your claw slot (or it's empty) and you have not selected a tool in the hotbar slot then you will get a multiplier to your block breaking speed
(Meaning it's the same behaviour as the modification to the harvest level)

This only takes effect when the `ServerConfig.bonusUnlockedAt` condition fulfilled
But it currently does not check if the dragon harvest type is effective for the broken block

You'd think only cave dragons can mine Stone faster since they are also the ones who get a harvest level bonus when `ServerConfig.bonusUnlockedAt` is reached - but thats not the case, all types get a bonus to all blocks in terms of block breaking speed

Adults also actually DO check for the dragon harvest type - to determine if they get a 4x multiplier or a 2x multiplier
(Meaning adult cave dragons mine stone 4x faster and dirt 2x faster)

#### Change
With the change the block breaking speed multiplier gets only applied to blocks the dragon type is effective against
Meaning cave dragons can mine pickaxe-blocks faster but not shovel-blocks

Adult dragons still get a base 2x multiplier to all blocks (and a 4x multiplier to their effective blocks)
This can be changed - I left it in because I was not sure if it was intentional or not
(For adult dragons to be faster at breaking blocks, independent to `ServerConfig.bonusUnlockedAt`)

---

### Harvest Level Modification
They way you described it is still valid

Using `ServerConfig.baseHarvestLevel` you can set a base harvest level which is independent of dragon type etc.
Meaning if you set that to 3 all dragons have diamond harvest level for all blocks
(This is 0 by default - meaning wood)

Using `ServerConfig.bonusHarvestLevel` you can set a bonus harvest level which applies to the block type the dragon is effective against (meaning pickaxe-blocks for cave dragons)
This only takes effect when `Serverconfig.bonusUnlockedAt` is reached

If you use a tool from the hotbar then `ServerConfig.bonusHarvestLevel` is not being applied and neither is the harvest level of the tool in your claw slot
(This is only relevant for tools - if you have a block or some non-tool in your hotbar selected then the bonus is applied etc.)

**Comment by SiverDX** [comment]
might be better to extract the mod compability stuff of this pr into its own mod
(jade, wthit harvestability, better combat and future things (e. g. adding curios or apotheosis affix button to the dragon inventory))

**Comment by BlackAures1** [comment]
> might be better to extract the mod compability stuff of this pr into its own mod

Did you write to them about it? I can hardly articulate correctly what they need to add and in general I don't know if they want to do it.

**Comment by SiverDX** [comment]
they dont need to add anything, there is stuff in this pr which adds certain compability
but it might be better to have its own mod for that

its more clean, causes less problems for the main mod and doesnt inflate its build.gradle

**Comment by BlackAures1** [comment]
You mean create a separate mod for dragon survival compatibility?

**Comment by BlackAures1** [comment]
What exactly would be the problem if all this compatibility was built into Dragon Survival?

**Comment by SiverDX** [comment]
if one compatibility has issues the mod has issues
(if one mod introduces breaking changes in a new version your mod has to be updated as well)

this list will get bigger
https://github.com/DragonSurvivalTeam/DragonSurvival/blob/2f6253b590c83b837c03cff2aa8652f7abbdd4ae/build.gradle#L137

you're potentially going to end up with bits and pieces in the code which is only there for compatibility

going to other versions could cause problems if the other mods have not been updated

---

ultimately i dont really know how minecraft mods normally handle this

jei has modules and those modules have other mods which expand their feature set
jade also has a mod for extended compatibility

don't think those are from the same author though

---

you could ask @FirDragon if they know more about this stuff

**Comment by BlackAures1** [comment]
Basically, it's the same as what I know. Thought there was something else.

Yes, let's have a separate mod for compatibility. Do you want it to be a branch in my repository and on my CF page or do you want to deal with it completely on your own?

**Comment by SiverDX** [comment]
Set up the mod, will do the Curse Forge stuff once this is merged (since it depends on the harvest changes)

This PR now affects the following:

---

### Fixed some issues regarding abilities (GUI)
* Tooltip coloring for increasing levels
* Experience gained from decreasing was 1 level lower than intended
* There were 2 additional SkillProgressButtons being rendered (but overlayed by other buttons)
* Right side of the experience cost for abilities had the wrong start location
* When increasing or decreasing ability levels all were shown as obtainable (until screen was re-opened)

### Other
* Removed bad omen application when you kill a knight (only occurred as a non-dragon)
* Fixed some issue with water cauldron block (sea dragon gained no good mana condition from it)

### Fixed a bug with the Claws and Teeth description
* The harvest level text was not accurate (starting from gold? it was 1 level too high)

### Fixed issues with harvesting
* Modded ore support for drops when only using paws (most modded ores should already work but this fixes certain other instances, mostly MCreator related)
* Config for bonusUnlockedAt is now respected
* ServerConfig.baseHarvestLevel is now actually used
* Minimum level for base and bonus level is now 0 (wood)
* When the tool in the claw inventory breaks block-breaking will no longer desync
* Block breaking speed is only applied if the dragon is effective against the block (e.g. cave dragon can mine pickaxe-blocks faster but not shovel-blocks)

### Removed Better Combat animation compatibility
(This will not cause Better Combat to now crash with Dragon Survival - that was a separate issue)
* Removed config

**Comment by BlackAures1** [comment]
Great. So I can already test this, publish it, and then you will publish your separate mod for compatibility on CF? That would be more convenient for both of us. You wouldn't have to wait for me and you would have complete freedom and I won't have to do this very testing and worry about broken things.

If you have everything ready, I can check it out today

**Comment by SiverDX** [comment]
Yeah this should be ready to test

**Comment by BlackAures1** [comment]
1. I understand this has happened before, but I'll keep it to myself as a note. This should not indicate the total bonus for using the claw panel. This tooltip is only for the innate base bonus, which the dragon has by default. It's not critical. It's just a little confusing. Iron sword gives 6 damage, and in the skill description instead of +2 it becomes +4


2. Judging by the testing in the old and new version was present before, I just paid attention to it only now. I have a datapack installed that changes the drop from the ore and adds two kinds of picks (good and bad). Only nuggets should fall from the bad ones (such as stone), but when I do it as a dragon with bare hand, I get vanilla drop + drop from datapack. Claws ignore datapacks on modified drop and tool checks?

https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/b497d0a2-bfd9-4dc5-8506-618dcf215f2e

I'll continue testing now, but so far these are the only problems I've noticed and they have essentially nothing to do with your Pull Request. These are just old bugs that were there before

**Pull request merged**
