### PR TITLE
Misc clean up

### PR DESCRIPTION
**Pull request by SiverDX**
- fix lava vision when in lava
- switch vehicle whitelist to entity tag
- clean up some item tags
- clean up MixinPlayer
- clean up MixinItemBlockRenderTypes
- clean up MixinEntity

### CODE REVIEW

**Comment by SiverDX** [comment]
Also atm when spawning a knight the game crashes due to missing model json

**Review by seelderr — CHANGES_REQUESTED** [review]
The name of the Mixin files should be Mixin(Classname), not the other way around. Otherwise looks good

**Comment by SiverDX** [comment]
personally I disagree just makes it harder to differentiate if all files start with mixin

**Comment by seelderr** [comment]
> personally I disagree just makes it harder to differentiate if all files start with mixin

we have been naming all of our mixin files Mixin(name), why change now?

**Comment by seelderr** [comment]
if you do want to change the format, rename all of the mixin files so it is consistent

**Comment by SiverDX** [comment]
> it is also pretty normal conventions, all the other mods i've worked on do the same format of Mixin(name)

fabric api (the official one) doesn't, neither do sodium and apotheosis dev or modernfix dev

> we have been naming all of our mixin files Mixin(name), why change now?

because in general the code base could need some cleanup especially in formatting etc

**Comment by SiverDX** [comment]
> if you do want to change the format, rename all of the mixin files so it is consistent

the plan would be to eventually go through all mixins and do that

**Comment by seelderr** [comment]
> > it is also pretty normal conventions, all the other mods i've worked on do the same format of Mixin(name)
> 
> fabric api (the official one) doesn't, neither do sodium, apotheosis dev or modernfix dev
> 
> > we have been naming all of our mixin files Mixin(name), why change now?
> 
> because in general the code base could need some cleanup especially in formatting etc

go for the change, i'm convinced, i might've been a bit mistaken. just make sure to rename them all like i said.

**Review by seelderr — APPROVED** [review]

**Pull request merged**
