### PR TITLE
1.20.1 major updates

### PR DESCRIPTION
**Pull request by Psither**
Updated the dragon editor file format to version 3.  Users can now select part color directly instead of selecting by hue offset.
Added automatic upgrading to existing customization files to avoid breaking existing configurations.
All mixins were re-written to improve compatibility with most mods.
Many, many bugfixes and refactors to make maintaining the code easier.

### CODE REVIEW

**Comment by BlackAures1** [comment]
image

**Comment by Psither** [comment]
All the issues should be fixed now.

**Comment by SomeoneYouKonw** [comment]
@seelderr, this, acctuly, will not fix #504. 
Just merged with fork of main repo, recompiled & checked - same error.

**Comment by SomeoneYouKonw** [comment]
I have discovered possible dedecatedserver tick crash relateing to ore drops. Will post more info as soon as I have any.

**Comment by SomeoneYouKonw** [comment]
> I have discovered possible dedecatedserver tick crash relateing to ore drops. Will post more info as soon as I have any.

UPD. 
Tests complete, and new info is just in:
- This crash is indeed caused by this update - none of the sympctoms are present when the mod is compiled from main repo. 
- Crash is not as much a crash, but just some error that causes long ticks, that, in turn, causes crash. The lower TPS on server - the worse it gets. 
- Problem above becomes less pronounced if pull is to be compiled from Psither:1.20.1-port, without marge with main repo. 
- This update make ores, that normaly drop elder dragon dust + resource not drop any loot most of times even when mining them does not kill the server. This problem stays constant.
- Logs to the gods of logs!:
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/15495556/latest.log)
[debug.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/15495579/debug.log)

Please, note: all tests has been run in a modpack, so mod conflict can not be eliminated.

**Comment by SiverDX** [comment]
seems like packages cannot be properly handled

https://github.com/Psither/DragonSurvival/blob/75c24f520e7d1f4ff322f9620ac1e30b21435630/src/main/java/by/dragonsurvivalteam/dragonsurvival/data/loot/DragonOreLootModifier.java#L64

don't remember clearly but I think that `Bound must be positive` also appears when you try `nextInt` with `0` (aka no fortune)

**Pull request merged**
