### PR TITLE
AppleSkin tooltips

### PR DESCRIPTION
**Pull request by SiverDX**
If a food is not suitable for the dragon type it's being displayed like this:
grafik

If you set `default` value too the tooltip seems to be empty (as in it is not shown) for foods which are not suitable
Maybe that would be preferred? Not sure

---

If it is suitable like this:
grafik

Some items may look like poison right now (e. g. `Spider Eyes` or `Charred` food) even though they're suitable
grafik

https://github.com/squeek502/AppleSkin/blob/8c861e80413c2fd578917f4d58e2cc8e54ba4508/java/squeek/appleskin/client/TooltipOverlayHandler.java#L161

https://github.com/squeek502/AppleSkin/blob/8c861e80413c2fd578917f4d58e2cc8e54ba4508/java/squeek/appleskin/helpers/FoodHelper.java#L52

Need to maybe do something with the food effects too

---

And custom food has no tooltip as of now
But it's a start

### CODE REVIEW

**Comment by SiverDX** [comment]
Tooltip is now correct if the item is edible for the dragon type
grafik

Tomorrow I'll try only overwriting the food values if the item is relevant for the dragon type and mark it as rotten otherwise
Might look and work better in general

**Comment by BlackAures1** [comment]
I had plans to do it differently. Just write the numbers around "Forest Dragon Food: 6/8" (based on config) and leave out the Apple Skin. What's the point of adding a dependency to a third-party mod when it can be built into the default DS tooltip? Also, the player, because of your way, is deprived of the chance to learn how this food works for other species and for humans.

**Comment by SiverDX** [comment]
Well this is an optional dependency, only being loaded when the player has AppleSkins installed 

And if they have they probably made a choice regarding the knowledge about food

**Comment by BlackAures1** [comment]
Yes, I understand that this is not mandatory compatibility (we already had compatibility in the past and even had textures inside the mod for that), but my plan was to make my own food display so that AppleSkin would be for human players, and the dragon food would be displayed like this:
image

AppleSkin has broken this compatibility in the past and we're tired of repairing it every time. If you could help me do something like above, I would be very grateful to you.

**Comment by SiverDX** [comment]
Can look into it (did something similar for myself to show mining speed on tools e. g.)

You might still want to keep an EventHandler for AppleSkin though, to disable the tooltip for dragons so you don't end up with an additional one which has wrong information

**Comment by BlackAures1** [comment]
if you remove the old compatibility pieces for AppleSkin I would appreciate it

**Comment by SiverDX** [comment]
You mean the things I added here? You will end up with double tooltips then though if you don't use `TooltipOverlayEvent.Pre` (and this part of the API has not changed for 2 years, you just need to cancel the event if the player is a dragon)

You can also create a second (compat) mod which only has code relevant for mod support, if you don't want that stuff here
It would have `Dragon Survival` as required dependency, so it can call the functions from it

**Comment by BlackAures1** [comment]
I don't quite know what you mean. I don't want compatibility with Apple Skin, and it doesn't make sense to have Apple Skin if we will have a built-in system for displaying saturation settings for dragons via existing tooltips. Apple Skin only shows food for human players, Dragon Survival will show food for each dragon species (without Apple Skin).

**Comment by SiverDX** [comment]
> Apple Skin only shows food for human players, Dragon Survival will show food for each dragon species (without Apple Skin).

Thats the thing, AppleSkin by default does not know that you are a dragon, so its tooltip will always be there
So you can do it two ways:
* You add compatibility with AppleSkin in just one way - you cancel the rendering of the tooltip if you are a dragon (there is pretty much no way for this to break since it is super simple, done through its API)
* You go through the entire tooltip with a very low priority on the ToolTip event handler and remove the AppleSkin tooltips manually (do not recommend)

**Comment by BlackAures1** [comment]
Why touch AppleSkin at all? The information about the dragon's stats is stored in the DS configs. AppleSkin has no contact with the DS food system at all. AppleSkin is also a client mod and if the player does not need this mod, he can simply not install it or turn it off in the configs for himself. Personally it would be useful for me to know the stats for both dragons and humans even if I only play as a dragon. After all, no one cancelled friends-humans.

**Comment by SiverDX** [comment]
Okay so:
1. There will be no compatibility in terms of dragon related food - AppleSkin will not receive that information
2. Player rendering for the tooltip would not be cancelled

Look at this - I only have the latest `Curseforge` versions of `Dragon Survival` and `AppleSkin`
But I can see food values and they have wrong values (since `AppleSkin` has no info about the actual values)
image

This is also true for new food from `Dragon Survival`
image

Which is why I propose to cancel `AppleSkins` rendering of said tooltip if you are a dragon and only show your variant in that case

**Comment by BlackAures1** [comment]
That's what I was talking about above - that part of the code for Apple Skin compatibility in DS (which we had before your commit a few years ago) is obsolete and needs to be completely removed to replace it with a separate system for DS. But as I say, I don't want to break the Apple Skin or completely disable it so that player dragons can see people options too (to offer food to friends for example)

**Comment by SiverDX** [comment]
The old code seems to be already removed

> I don't want to break the Apple Skin or completely disable it so that player dragons can see people options too (to offer food to friends for example)

Ok I undestand what you mean now
But this will be very confusing since players are used to the fact that the values displayed there will be the (current) food benefit
And with a `Dragon Survival` system they now have two conflicting information - it's not quite UI friendly imo

**Comment by BlackAures1** [comment]
As I said before - Apple Skin is a mod client. The player can disable it and join the server without problems. If the dragon player doesn't need the Apple Skin, he will disable it or not install it. But your idea can also be implemented as a config. Add a config that will remove AppleSkin tooltips for dragons. That would be a perfect solution to the problem

**Comment by SiverDX** [comment]
There are multiple ways the icon can be done

You can use the default food icon:

image

---

Or you create custom icons (which is what I implemented now):

image

(Yeah need to change the color on this one)
image

image

Appending the `0` in front of numbers < 10 is optional, can remove that

**Comment by SiverDX** [comment]
I'm actually realizing something now
In the example I thought it was only the nutrition value and it was basically `x out of maximum player nutrition`

But it's actually Nutrition / Saturation

Gonna change  that

**Comment by SiverDX** [comment]
Also saw something in regards how tooltips do not appear on items with bad effects
That is intentional:

https://github.com/DragonSurvivalTeam/DragonSurvival/blob/c1115f38cba352539898414395d404242d9b6502/src/main/java/by/dragonsurvivalteam/dragonsurvival/common/handlers/DragonFoodHandler.java#L248

**Comment by BlackAures1** [comment]
Thank you so much for your update! It is very helpful! I will try to check it out soon.

Hmm, how does the fact that pufferfish retains the nausea effect and the fact that the edibility of this food (and other food with negative effects) is not shown by the dragon's tooltip? Pufferfish nausea is what is planned. Dragon tooltips don't appear and there are other negative effects is a bug.

**Comment by SiverDX** [comment]
`!e.isBeneficial()` if a food item has a effect which is not beneficial (and said effect is not the confusion effect) it will not get added to the list of dragon foods, since it is not considered safe

**Comment by BlackAures1** [comment]
Okay, then the quickest fix is just to delete this line, as I understand it

**Pull request merged**
