### PR TITLE
Smol door

### PR DESCRIPTION
**Pull request by maleus1**
Adds small dragon doors (1x1 size). I've tested all normal door functionality works.
- Couldn't find item textures (icons in inventory) so just used the normal dragon door ones.
- Missing recipes, let me know if you want me to add them.

### CODE REVIEW

**Comment by Horeak** [comment]
java_y40WXqoIdU

The small doors are currently missing face at the bottom which is not the case for other doors, aswell as not updating when the block below is broken therefor allowing floating doors. 

Other then that it seems good.

**Comment by maleus1** [comment]
Thanks for the review. All the issues should be fixed now.
- Added some new models with faces on all sides, to fix missing face.
- Fixed the issue that allowed floating doors.
- Updated item textures based on discussion with blackaures

**Comment by maleus1** [comment]
Looks like the build failed due to gradle package install issues, I don't think its related to my changes.

**Comment by Horeak** [comment]
Your are correct there, just need to get a confirmation from @BlackAures1 then it can be merged.

**Comment by BlackAures1** [comment]
Thanks for the little doors! :3

**Pull request merged**
