### PR TITLE
[Fix] Fixed an issue where mana cost was doubled when using magic in …

### PR DESCRIPTION
**Pull request by FirDragon**
Fixed an issue where using mana on a server would double the mana cost if the server load or network latency was high. Note that this is not the best fix, but it solves the problem temporarily.

The reason for this bug is a logic error in the synchronization magic part.
The current logic is
[ClientCastingHandler.abilityKeyBindingChecks] is activated when the shortcut key to cast magic is pressed,
[SyncAbilityCasting] will send [chargeTime] information to indicate the duration of the current press when Dragon Breath is selected. But the update of the duration of pressing comes from [ChargeCastAbility.onKeyPressed] of the server, and then the server sends [chargeTime++] back to the client.
When there is a triple delay, the value update effect of [chargeTime] is:
client: 0
client: 0
client: 0
server: 1
client: 1
server: 1
client: 1
server: 1
client: 1
server: 2
However, since the judgment of mana reduction is based on [chargeTime==mana consumption when the casting time is long], it will consume multiple times of mana at one time.

### CODE REVIEW

**Comment by FirDragon** [comment]
Although #231 has been closed, the problem still exists in actual testing

**Comment by BlackAures1** [comment]
Thanks for the fix!

**Comment by FirDragon** [comment]
You're welcome >w<, feel free to close this request if you have a better fix idea. owo

**Comment by BlackAures1** [comment]
Can I ask you to help me fix the problem that the dragon's appearance is not saved after using the altar? This started happening on the githab version and I can't find what's causing it right now. I can't post updates publicly for this reason.

**Pull request merged**
