### PR TITLE
backport from 1.19.2

### PR DESCRIPTION
**Pull request by SiverDX**
no guarantees™

doesn't immediately crash (threw it into the 1.18 modpack), things look fine i guess (tested some of the latest changes i did)
prob beta at most, you should test this if you want to release it

### CODE REVIEW

**Comment by BlackAures1** [comment]
Wow! That's cool that you decided to join the backport.  I'm personally stuck on the part where the altar doesn't save the dragon's appearance.  I never could figure out what was causing it.

**Comment by SiverDX** [comment]
Test .jar without double popPose call

[DragonSurvival-1.18.2-1.5.47.zip](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12137467/DragonSurvival-1.18.2-1.5.47.zip)

**Comment by FirDragon** [comment]
Well done!

**Comment by BlackAures1** [comment]
Sorry for the delay in checking this pull-request, I'm actively working on a new update right now.

**Pull request merged**
