### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by SiverDX**
Currently trying some things out, still WIP
Posting here in case other developers have some input / ideas / are working on sth. similar

MixinBlock
* Made it more readable because I was looking into a problem
* Check for ServerLevel first because why not

DragonStateHandler
* Probably need to write and read `hasWings` and `spinLearned` even if not in dragon form?
* Haven't done this yet

MixinEnchantmentHelper : getEnchantmentLevel
* Seems like this can get constantly called - try to only use mixed-in code if relevant
* Might need to change this up a bit?

MixinPlayerEntity
* Changed some `Redirect` mixins to other types to avoid compatibility problems with `BetterCombat`
* Added a mixin to avoid the breaking of items in main hand

---

The changes to `MixinPlayerEntity` seem to have some problems with certain mods?
* The damage and enchantment values of the dragon tool are being used
* But in my modpack non-relevant items are still being destroyed (not in the IDE though)
(Fun fact: this does not seem to be the case in the `Play as Dragon Gothic Edition` modpack)

### CODE REVIEW

**Comment by SiverDX** [comment]
Seems like the issue for blocks not dropping resources is here (`ServerPlayerGameMode`):
image

which calls the hardcoded part that uses `Item var6 = player.getInventory().getSelected().getItem();`

**Comment by SiverDX** [comment]
Never mind the commit comment about the enchants - confused `Fortune` with `Silk Touch`
Both work for dragon tool slot

**Comment by BlackAures1** [comment]
Keep in mind that part of the code is written to make the claws work with the [ore-excavation](https://www.curseforge.com/minecraft/mc-mods/ore-excavation) mod

**Comment by SiverDX** [comment]
Should not be impacted, still functions

Though the dragon tool slot does not seem to work for MCreator ores, even before the changes (what a surprise)
Maybe other too, not sure - `Zinc` works at least

**Comment by SiverDX** [comment]
# Current status
* Better performance regarding echantments by not checking armor enchants for dragon state related things
* Improved compatibility for the `Better Combat` mod (incl. option to not render the model in first person)
* Less problems with modded blocks not dropping resources (e.g. MCreator generated things)
* Wings and learned spin move should now be properly saved
* Dragon sword should be more compatible regarding everything (no more breaking items in main hand, better enchantment support etc.)
* Cooldowns are now configured in seconds - old configs will need to be updated / reset

**Comment by SiverDX** [comment]
image

Is this a case of old tick values not having been updated? They are already supposed to be seconds but look more like tick values instead (at least the `110`, `310` and `1010` (which would be 16 minutes as seconds but 50 seconds as tick value))

**Comment by SiverDX** [comment]
Upgraded Netherite items do not seem to be updated in here

image

image


Which is why they are unaffected by blacklisting
Probably need to add an additional check where you get the currently selected slot and compare them

**Comment by BlackAures1** [comment]
> Is this a case of old tick values not having been updated? They are already supposed to be seconds but look more like tick values instead (at least the 110, 310 and 1010 (which would be 16 minutes as seconds but 50 seconds as tick value))

Additional +10 seconds is leveling the time that the player spends waiting to get the buff, which lasts 10 seconds. Or did I misunderstand your question?

**Comment by SiverDX** [comment]
Meant more the other values
* Elder Dragon Dust lasts 20 seconds
* Elder Dragon Bone lasts 60 seconds

Are these correct:
* Weak Heart Shard lasts 110 seconds
* Weak Dragon Heart lasts 310 seconds
* Elder Dragon Heart lasts 1010 seconds

**Comment by BlackAures1** [comment]
Dust +10 sec
Elder Dragon Bone +50 sec
Weak Heart Shard +100 
etc

**Comment by BlackAures1** [comment]
> Which is why they are unaffected by blacklisting
> Probably need to add an additional check where you get the currently selected slot and compare them

Yes, it is required.

**Comment by BlackAures1** [comment]
I tested this in single player + on a dedicated server with no other players and generally found no problems.
If you think it's ready, I can add it to the main thread and post an update

**Comment by SiverDX** [comment]
It's probably ready - did not find any issues myself so far

Problematic part is getting people to change / reset the config (e.g. for cooldowns or the off hand slot)

**Comment by BlackAures1** [comment]
Our users have long been trained to delete configs after updates. If that doesn't help, we'll do it: 
image

**Pull request merged**
