### PR TITLE
Cleaned up DragonBallEntity code and fixed #456

### LINKED ISSUE #456: [1.19.2 Bug]: Fireball doesnt damage
### ■ Your Discord ID or other contacts

void.dragon

### ■ Dragon Survival version

DragonSurvival-1.19.2-02.03.2024_stable.jar

### ■ Single game or server?

Single-player (Default)

### !!!This is also applicable to LAN!!!

Playing as a Cave dragon, most of the time when using the second ability, the fireball doesn't seem do anything after landing on the targeted enemy, no knockback, damage or anything. This bug mainly happens after the first fireball lands and works correctly and then try again after the cooldown finishes completely. The fireball goes out, makes an explosion sound on impact but does nothing else. I am fully aware there is a max range, but I know its landing on the target and within range.

Until this is sorted, I'll have to change my dragon type at a alter as this seems to be exclusive to only cave dragons as far as I am aware of. It's no big deal, but I love being able to swim/mine in lava. 

Water and Forrest dragons do not seem to be able to reproduce this issue with their 2nd ability that is similar to fireball.

### ■ Crash Report File and Logs

_No response_

### PR DESCRIPTION
**Pull request by seelderr**
Fixed inconsistent explosion damage with FireBallEntity, and prevented dragons from being able to damage themselves with their own explosions.

### CODE REVIEW

**Comment by zschect** [comment]
fixes #456

**Comment by zschect** [comment]
going to update this more tommorow. there is an issue with the self-damage prevention code at the moment: if the owner of the explosion is the player, it actually causes them to not be included in the check that deals damage to entities when explosion() is called. 

so with current behavior the player actually can't damage themselves anyways. might scrap the SubscribeEvent and just let all dragon projectiles not be able to damage the owner, or work out some more complex solution here.

**Comment by BlackAures1** [comment]
I'm fine with all projectiles not doing damage. Can this be added as a config option?

**Comment by seelderr** [comment]
ok, fixed up a few bugs with the implementation and removed the config option for cave dragons. the reason being that the fireball does fire damage, which the cave dragon is already immune to. so i'd either have to change the damage type or write some code that would make it ignore resistance for just the cave dragon that shot it. which feels like more effort than it is worth for a non-default option, so i just removed the config for cave dragons.

**Pull request merged**
